# Cloudflare Workers Configuration for Claude Code Router
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "claude-code-router-1016"
main = "src/workers.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "bun run build:workers"

# Environment variables for development
[vars]
LOG_LEVEL = "info"
HOST = "0.0.0.0"
PORT = "3456"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
